services:

  mysql:
    image: mysql:8
    container_name: mysql_todo
    restart: always
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: todo_api
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/todo_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      DB_USER: todo_user
      DB_PASSWORD: todo_pass

volumes:
  mysql_data:
